'use strict';
const C=require('../game-core.js');
class Clock{constructor(){this.now=0;this.next=1;this.jobs=new Map();this.history=[]}set(fn,ms){const id=this.next++;this.jobs.set(id,{id,fn,at:this.now+ms});this.history.push(fn);return id}clear(id){this.jobs.delete(id)}tick(ms){const target=this.now+ms;let n=0;while(true){const task=[...this.jobs.values()].filter(j=>j.at<=target).sort((a,b)=>a.at-b.at||a.id-b.id)[0];if(!task)break;if(++n>10000)throw Error('Runaway timers');this.now=task.at;this.jobs.delete(task.id);task.fn()}this.now=target}scheduler(){return {set:this.set.bind(this),clear:this.clear.bind(this)}}}
class MemoryStorage{constructor(){this.values=new Map();this.fail=false}getItem(k){return this.values.get(k)||null}setItem(k,v){if(this.fail)throw Error('QuotaExceededError');this.values.set(k,String(v))}}
function fixture(){const clock=new Clock(),messages=[];const e=new C.Engine({seed:1,scheduler:clock.scheduler(),random:()=>.5,onMessage:t=>messages.push(t)});return {e,clock,messages}}
function place(e,id,x,y){if(!C.passable(x,y))throw Error('Bad fixture cell '+x+','+y);Object.assign(e.s.heroes[id],{x,y});C.reveal(e.s)}
function near(e,id,objectId){const path=C.pathToInteract(e.s,id,objectId);if(!path)throw Error('No fixture approach '+objectId);if(path.length)place(e,id,...path.at(-1));else C.reveal(e.s)}
function duel(){const f=fixture(),{e}=f;place(e,'arden',8,2);e.startBattle('arden',{kind:'object',id:'object-8-3'});e.cancelTimer();const b=e.s.battle;e.s.heroes.arden.army={pikes:1,bows:0,cavs:0,griffins:0,mages:0};b.stacks=[{id:'p',side:'p',type:'pikes',qty:1,hp:9,initialQty:1,x:0,y:0,defending:false,stone:false,counterRound:0},{id:'e',side:'e',type:'orcs',qty:100,hp:1400,initialQty:100,x:7,y:1,defending:false,stone:false,counterRound:0}];Object.assign(b,{order:['p','e'],index:1,round:1,turnId:1,selectedId:'p',phase:'player'});return {...f,b,p:b.stacks[0],enemy:b.stacks[1]}}
module.exports={Clock,MemoryStorage,fixture,place,near,duel};
