/* Minimal DOM adapter, deliberately not a browser layout/rendering implementation. */
'use strict';
const fs=require('fs'),path=require('path'),{Clock,MemoryStorage}=require('./helpers.cjs');
const decode=s=>String(s).replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'");
function matchSimple(node,selector){if(!node.tagName)return false;let ok=true;selector=selector.replace(/:not\(([^)]+)\)/g,(_,inner)=>{if(matchSimple(node,inner))ok=false;return ''});if(!ok)return false;const tag=selector.match(/^[a-z][a-z0-9-]*/i)?.[0];if(tag&&node.tagName!==tag.toLowerCase())return false;for(const [,name]of selector.matchAll(/\.([\w-]+)/g))if(!node.classList.contains(name))return false;const id=selector.match(/#([\w-]+)/)?.[1];if(id&&node.id!==id)return false;for(const [,name,,value]of selector.matchAll(/\[([\w-]+)(?:=(['"]?)([^\]'"]+)\2)?\]/g)){let actual=node.getAttribute(name);if(name==='disabled')actual=node.disabled?'':null;if(name==='hidden')actual=node.hidden?'':null;if(actual===null)return false;if(value!==undefined&&actual!==value)return false}return true}
function matches(node,selector){const parts=selector.trim().split(/\s+(?![^[]*\])/);if(!matchSimple(node,parts.pop()))return false;let p=node.parentNode;while(parts.length){const part=parts.pop();while(p&&!matchSimple(p,part))p=p.parentNode;if(!p)return false;p=p.parentNode}return true}
class Element{
 constructor(tag,doc){this.tagName=tag;this.ownerDocument=doc;this.children=[];this.parentNode=null;this.attributes={};this.dataset={};this.style={};this._text='';this._html='';this.id='';this.className='';this.disabled=false;this.hidden=false;this.inert=false;this.listeners={};this.files=[];this.value='';const self=this;this.classList={contains:k=>self.className.split(/\s+/).includes(k),add:k=>{const s=new Set(self.className.split(/\s+/).filter(Boolean));s.add(k);self.className=[...s].join(' ')},remove:k=>self.className=self.className.split(/\s+/).filter(c=>c!==k).join(' '),toggle:(k,on)=>{if(on===undefined)on=!self.classList.contains(k);on?self.classList.add(k):self.classList.remove(k)}}}
 appendChild(child){child.parentNode=this;this.children.push(child);return child}
 remove(){if(this.parentNode)this.parentNode.children=this.parentNode.children.filter(c=>c!==this);this.parentNode=null}
 setAttribute(k,v){v=String(v);this.attributes[k]=v;if(k==='id')this.id=v;if(k==='class')this.className=v;if(k==='disabled')this.disabled=true;if(k==='hidden')this.hidden=true;if(k==='value')this.value=v;if(k.startsWith('data-'))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=v}
 getAttribute(k){if(k==='id')return this.id||null;if(k==='class')return this.className||null;return Object.hasOwn(this.attributes,k)?this.attributes[k]:null}
 get isConnected(){let p=this;while(p){if(p===this.ownerDocument.root)return true;p=p.parentNode}return false}
 set innerHTML(v){this._html=String(v);this._text='';this.children=[];parse(this._html,this,this.ownerDocument)}get innerHTML(){return this._html}
 set textContent(v){this._text=String(v);this._html=String(v);this.children=[]}get textContent(){return this._text+this.children.map(n=>n.textContent).join('')}
 querySelectorAll(selector){const selectors=selector.split(','),result=[];function visit(n){for(const c of n.children){if(selectors.some(s=>matches(c,s)))result.push(c);visit(c)}}visit(this);return result}
 querySelector(s){return this.querySelectorAll(s)[0]||null}
 addEventListener(k,fn){(this.listeners[k]||=[]).push(fn)}
 emit(k,e={}){const event={target:this,preventDefault(){},...e};for(const fn of this.listeners[k]||[])fn(event)}
 click(){if(!this.disabled)this.onclick?.({target:this,preventDefault(){}})}
 focus(){this.ownerDocument.activeElement=this}
 getBoundingClientRect(){return {left:0,top:0,width:390,height:650}}
 setPointerCapture(id){this.capture=id}hasPointerCapture(id){return this.capture===id}releasePointerCapture(){this.capture=null}
 getContext(){const doc=this.ownerDocument;return new Proxy({measureText:t=>({width:String(t).length*16}),drawImage:(img,...args)=>{if(!img)throw Error('Undefined image');doc.drawn.push(img.src||'canvas')},globalAlpha:1,createPattern:()=>({}),createLinearGradient:()=>({addColorStop(){}}),createRadialGradient:()=>({addColorStop(){}})},{get:(o,k)=>o[k]||(()=>{})})}
}
function parse(html,parent,doc){const stack=[parent],voids=new Set(['meta','link','img','input','br','hr']);for(const token of html.match(/<!--[\s\S]*?-->|<![^>]*>|<\/?[^>]+>|[^<]+/g)||[]){if(token.startsWith('<!'))continue;if(token.startsWith('</')){const tag=token.slice(2).match(/^[\w-]+/)?.[0];for(let i=stack.length-1;i>0;i--)if(stack[i].tagName===tag){stack.length=i;break}continue}if(token[0]==='<'){const tag=token.slice(1).match(/^[\w-]+/)?.[0];if(!tag)continue;const el=new Element(tag.toLowerCase(),doc);const attrs=token.slice(tag.length+1,-1);for(const [,name,,quoted,plain]of attrs.matchAll(/([\w:-]+)(?:\s*=\s*(?:(["'])(.*?)\2|([^\s>]+)))?/g))el.setAttribute(name,decode(quoted??plain??''));stack.at(-1).appendChild(el);if(!voids.has(tag)&&!token.endsWith('/>'))stack.push(el)}else stack.at(-1)._text+=decode(token)}}
function environment({missing=[],hang=[],storage=new MemoryStorage()}={}){const clock=new Clock(),doc={activeElement:null,hidden:false,drawn:[],listeners:{}};doc.root=new Element('document',doc);parse(fs.readFileSync(path.join(__dirname,'../index.html'),'utf8'),doc.root,doc);doc.body=doc.root.querySelector('body');doc.getElementById=id=>{const list=[doc.root,...doc.root.querySelectorAll('*')];return list.find(n=>n.id===id)||null};doc.querySelectorAll=s=>doc.root.querySelectorAll(s);doc.querySelector=s=>doc.root.querySelector(s);doc.createElement=tag=>new Element(tag,doc);doc.addEventListener=(k,fn)=>(doc.listeners[k]||=[]).push(fn);doc.activeElement=doc.body;const frames=new Map();let frameId=0;const env={document:doc,localStorage:storage,setTimeout:clock.set.bind(clock),clearTimeout:clock.clear.bind(clock),requestAnimationFrame:fn=>{const id=++frameId;frames.set(id,fn);return id},devicePixelRatio:1,matchMedia:()=>({matches:false}),addEventListener(){},location:{protocol:'file:'},navigator:{},isSecureContext:false,confirm:()=>true,Image:class{set src(v){this._src=v;if(!hang.includes(v))queueMicrotask(()=>missing.includes(v)?this.onerror?.():this.onload?.())}get src(){return this._src}},Blob,URL:{createObjectURL:()=> 'blob:test',revokeObjectURL(){}}};return {env,doc,clock,storage,frames,frame(t){const callbacks=[...frames.values()];frames.clear();for(const fn of callbacks)fn(t)}}}
module.exports={environment};
