'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),vm=require('node:vm');
const S=require('../scene-renderer.js'),B=require('../scene-battle.js'),C=require('../game-core.js'),H=require('./helpers.cjs'),R=require('./render-contracts.cjs'),UI=require('../game-ui.js'),{environment}=require('./mock-dom.cjs');
const root=path.join(__dirname,'..'),read=n=>fs.readFileSync(path.join(root,n),'utf8'),results=[];
async function test(id,name,fn){try{await fn();results.push({id,name,status:'pass'})}catch(e){results.push({id,name,status:'fail',error:e.stack});console.error(id,e.message)}}
(async()=>{
await test('P01','Gameplay modules and data identical to 9.2.0 except version',()=>{const refs=JSON.parse(read('qa/gameplay-baseline.json'));for(const [n,hash]of Object.entries(refs)){let data=n.includes('normalized')?read('game-data.js').replaceAll('9.2.1','VERSION'):read(n);assert.equal(crypto.createHash('sha256').update(data).digest('hex'),hash,n)}});
await test('P02','Floor detail is deterministic, clipped and varies by position',()=>{const render=(x,y)=>{const h=R.context();S.floorDetail(h.ctx,{x:100,y:100},78,42,x,y);return h.calls};assert.deepEqual(render(1,2),render(1,2));assert.notDeepEqual(render(1,2),render(2,2));assert(render(1,2).some(c=>c[0]==='clip'))});
await test('P03','Dungeon scenery does not enter hit targets or mutate campaign',()=>{const h=R.worldFixture(true),before=JSON.stringify(h.e.s);h.world.draw(h.e.s,h.m,null,1234);assert.equal(JSON.stringify(h.e.s),before);assert(h.world.hitAreas.every(o=>C.D.dungeon.objects.some(d=>d.id===o.id)));assert(new Set(h.world.scenery.map(o=>o.h)).size>4);assert(h.world.scenery.every(o=>!o.handler&&!o.action))});
await test('P04','Static floor cache remains unchanged across frames',()=>{const h=R.worldFixture(true),base=h.world.base;h.world.draw(h.e.s,h.m,null,0);h.world.draw(h.e.s,h.m,null,600);assert.equal(h.world.base,base);assert.equal(h.world.staticBuilds,1)});
await test('P05','Battle draw, shadows and impact do not mutate committed result',()=>{const h=R.harness(),{b}=H.duel(),scene=new B.BattleScene(h.canvas,h.doc,h.assets);scene.observe(b,0,14);b.stacks[1].hp-=2;scene.observe(b,10,14);const before=JSON.stringify(b);scene.draw(b,120);const base=scene.base;scene.draw(b,340);assert.equal(scene.base,base);assert.equal(JSON.stringify(b),before);assert(scene.timeline.events.some(e=>e.damage===2))});
await test('P06','Animation timing preserved from baseline; impact is a 300ms overlay',()=>{const {b}=H.duel(),t=new B.BattleTimeline();t.observe(b,0,14);b.stacks[1].hp-=2;t.observe(b,10,14);assert(t.busy(650));assert(!t.busy(711));assert(read('scene-battle.js').includes('now-e.start<300'));assert(!read('scene-battle.js').includes('setTimeout'))});
await test('P07','Initiative markup preserves exact model order and quantities',async()=>{const h=environment(),a=new UI.App(h.env);await a.boot();const {b}=H.duel();a.engine.s.battle=b;a.renderBattle();const html=a.$('turnbar').innerHTML;const labels=[...html.matchAll(/aria-label="([^" ]+)[^"]*/g)];assert.equal(labels.length,b.order.length);const expected=b.order.map(id=>b.stacks.find(s=>s.id===id));expected.forEach((st,i)=>assert(labels[i][0].includes(C.stackDef(st).n)));assert(html.includes('aria-current="true"'));assert(!html.includes('…'));const key=a.queueKey;a.renderBattle();assert.equal(a.queueKey,key)});
await test('P08','Every initiative portrait exists with exact case',()=>{for(const def of [...Object.values(C.D.units),...Object.values(C.D.enemies)]){assert(fs.readdirSync(root).includes(def.img),def.img)}});
await test('P09','Water and lava animation stays inside clipped strips',()=>{const code=read('scene-battle.js');assert(code.includes('S.diamond(ctx,q,this.rx,this.ry);ctx.clip()'));assert(read('scene-renderer.js').includes("if(!['water','lava','bridge'].includes(kind))continue"));assert(!read('game.css').includes('filter:brightness'))});
await test('P10','SW precache bypasses HTTP cache while retaining canonical URLs',async()=>{const events={},requests=[];vm.runInNewContext(read('sw.js'),{URL,Request,Set,Promise,self:{registration:{scope:'https://example.test/game/'},addEventListener:(k,f)=>events[k]=f},caches:{open:async()=>({addAll:async list=>requests.push(...list)})}});let pending;events.install({waitUntil:p=>pending=p});await pending;assert(requests.length>30);assert(requests.every(r=>r.cache==='reload'));assert(requests.some(r=>r.url.endsWith('/assets/actors-v2.png')))});
await test('P11','Active release metadata agrees',()=>{assert.equal(C.D.VERSION,'9.2.1');for(const n of ['index.html','game-data.js','manifest.webmanifest','sw.js','package.json']){assert(read(n).includes('9.2.1'));assert(!read(n).includes('9.2.0'))}});
const failed=results.filter(r=>r.status==='fail').length;fs.writeFileSync(path.join(root,'qa/polish-results.json'),JSON.stringify({total:results.length,passed:results.length-failed,failed,results},null,2));console.log(JSON.stringify({total:results.length,passed:results.length-failed,failed}));process.exitCode=failed?1:0;
})();
