'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const C=require('../game-core.js'),{Camera,Projection}=require('../scene-camera.js'),Controls=require('../game-controls.js'),S=require('../scene-renderer.js'),B=require('../scene-battle.js'),M=require('../music-engine.js'),H=require('./helpers.cjs'),R=require('./render-contracts.cjs'),UI=require('../game-ui.js'),{environment}=require('./mock-dom.cjs');
const results=[];async function test(id,name,fn){try{await fn();results.push({id,name,status:'pass'})}catch(e){results.push({id,name,status:'fail',error:e.stack});console.error(id,name,e.message)}}
const close=(a,b)=>assert(Math.abs(a-b)<1e-7,`${a} != ${b}`);
function dungeon(){const h=H.fixture();h.e.enterDungeon('arden');h.e.s.dungeon.seen=Array.from({length:130},(_,i)=>C.key(i%13,Math.floor(i/13)));return h}
async function app(){const h=environment();h.env.cancelAnimationFrame=id=>h.frames.delete(id);h.app=new UI.App(h.env);await h.app.boot();return h}
function audio(){const voices=[],buses=[];const param=()=>({value:0,setValueAtTime(){},exponentialRampToValueAtTime(){},linearRampToValueAtTime(){},setTargetAtTime(){}});return {currentTime:0,state:'running',destination:{},voices,buses,createGain(){const n={gain:param(),connect(){},disconnect(){this.disconnected=true}};buses.push(n);return n},createBiquadFilter(){return {frequency:param(),connect(){},disconnect(){}}},createOscillator(){const n={frequency:param(),connect(){},disconnect(){},start(){},stop(){this.stopped=true}};voices.push(n);return n}}}
async function main(){
await test('R01','World/projected/screen round-trips across all cells and zooms',()=>{const p=new Projection(26,20),c=new Camera({worldWidth:p.worldWidth,worldHeight:p.worldHeight});for(const z of [.35,.72,1.65]){c.zoom=z;c.x=401;c.y=287;for(let y=0;y<20;y++)for(let x=0;x<26;x++){const q=p.cell(x,y),screen=c.worldToScreen(q),back=c.screenToWorld(screen);close(q.x,back.x);close(q.y,back.y);assert.deepEqual(p.hit(back.x,back.y),{x,y})}}});
await test('R02','Pinch/zoom preserves world point beneath finger',()=>{const c=new Camera({worldWidth:4000,worldHeight:3000});c.centerOn(1800,1200);const q=c.screenToWorld(123,222);c.zoomAt(1.4,123,222);const r=c.screenToWorld(123,222);close(q.x,r.x);close(q.y,r.y)});
await test('R03','Viewport resize preserves camera focus and pending animation',()=>{const c=new Camera({worldWidth:4000,worldHeight:3000,viewportWidth:1280,viewportHeight:800});c.centerOn(1600,1400);c.animateTo(1800,1700);const q=c.screenToWorld(640,448),target={...c.target};c.resize(390,740);const r=c.screenToWorld(195,414.4);close(q.x,r.x);close(q.y,r.y);assert(c.target.x>target.x);assert(c.ready)});
await test('R04','Camera clamp handles undersized world without NaN',()=>{const c=new Camera({worldWidth:100,worldHeight:80});c.x=Infinity;c.zoom=NaN;c.clamp();assert(Number.isFinite(c.x)&&Number.isFinite(c.y));const prior=c.viewportWidth;c.resize(0,0);assert.equal(c.viewportWidth,prior)});
await test('R05','Tap selects a real projected castle sprite',async()=>{const h=await app();h.app.drawMap(0);const hit=h.app.worldScene.hitAreas.find(o=>o.id==='castle');assert(hit);const q=h.app.camera.worldToScreen(hit.x+hit.w/2,hit.y+hit.h/2);h.app.mapTap(q.x,q.y);assert.equal(h.app.selection,'castle')});
await test('R06','Ground tap schedules a valid path without teleporting',async()=>{const h=await app(),a=h.app,e=a.engine;const q=a.camera.worldToScreen(a.worldScene.projection.cell(13,8));a.worldScene.hitAreas=[];a.mapTap(q.x,q.y);assert(e.s.movement);assert.equal(e.s.heroes.arden.x,12);assert.deepEqual(e.s.movement.path.at(-1),[13,8])});
await test('R07','Surface interpolation belongs only to movement owner',()=>{const {e}=H.fixture(),m=new Controls.MotionDriver(e);e.commandMove('arden',13,8);m.frame(0);m.frame(165);assert(m.position('arden').x>1250&&m.position('arden').x<1350);assert.equal(m.position('lyra').x,1450);assert.equal(e.s.heroes.arden.x,12);m.frame(330);assert.equal(e.s.heroes.arden.x,13)});
await test('R08','All active building footprints block transit; all approaches remain reachable',()=>{const {e}=H.fixture();e.s.enemy.alive=false;for(const o of C.D.objects)if(o.t==='enemy')e.s.objects[o.id].status='defeated';for(const o of C.D.objects)if(C.solidAt(e.s,o.x,o.y)){assert.equal(C.pathfind(e.s,'arden',o.x,o.y),null);assert.notEqual(C.pathToInteract(e.s,'arden',o.id),null)}});
await test('R09','An imported route cannot cross a newly solid building',()=>{const {e}=H.fixture();e.s.movement={id:'stale',heroId:'arden',path:[[12,7]],targetId:null};const before=e.s.heroes.arden.moves;e.movementStep('stale');assert.equal(e.s.movement,null);assert.equal(e.s.heroes.arden.y,8);assert.equal(e.s.heroes.arden.moves,before)});
await test('R10','Fog has UNKNOWN EXPLORED VISIBLE states and does not mutate exploration',()=>{const h=R.harness(),f=h.world.fog,seen=['1,1','10,10'];f.update(seen,[{x:10,y:10}]);assert.equal(f.state(1,1),'EXPLORED');assert.equal(f.state(10,10),'VISIBLE');assert.equal(f.state(20,15),'UNKNOWN');assert.deepEqual(seen,['1,1','10,10'])});
await test('R11','Hidden static and roaming objects are not hit targets',()=>{const h=R.worldFixture();h.e.s.seen=[];h.e.s.heroes.arden.x=1;h.e.s.heroes.arden.y=1;h.e.s.heroes.lyra.x=1;h.e.s.heroes.lyra.y=1;h.world.draw(h.e.s,h.m,null,0);assert(!h.world.hitAreas.some(o=>o.id==='morvein-field'||o.id==='necropolis'))});
await test('R12','Dungeon motion commits exactly one cell after interpolation',()=>{const {e}=dungeon(),m=new Controls.DungeonMotionDriver(e);assert(m.command(3,8).ok);const before=e.s.heroes.arden.moves;m.frame(0);m.frame(140);assert.equal(e.s.dungeon.x,1);assert(m.position().x>150&&m.position().x<250);m.frame(280);assert.equal(e.s.dungeon.x,2);assert.equal(e.s.heroes.arden.moves,before-1);m.frame(300);m.frame(580);assert.equal(e.s.dungeon.x,3)});
await test('R13','Dungeon route is cancelled on day change without consuming new movement',()=>{const {e}=dungeon(),m=new Controls.DungeonMotionDriver(e);m.command(3,8);m.frame(0);e.nextDay();const moves=e.s.heroes.arden.moves;m.frame(1000);assert.equal(e.s.dungeon.x,1);assert.equal(e.s.heroes.arden.moves,moves);assert.equal(m.route,null)});
await test('R14','Dungeon route does not move another selected hero',()=>{const {e}=dungeon(),m=new Controls.DungeonMotionDriver(e);m.command(3,8);m.frame(0);e.s.activeHero='lyra';m.frame(1000);assert.equal(e.s.dungeon.x,1);assert.equal(m.route,null)});
await test('R15','A final movement point still allows adjacent enemy interaction',()=>{const {e}=dungeon(),m=new Controls.DungeonMotionDriver(e);e.s.dungeon.x=3;e.s.dungeon.y=8;e.s.heroes.arden.moves=1;assert(m.command(4,7,'d-guard').ok);m.frame(0);m.frame(280);m.frame(300);assert.equal(e.s.battle?.source.id,'d-guard')});
await test('R16','Unseen dungeon targets cannot be approached or activated remotely',()=>{const {e}=dungeon(),m=new Controls.DungeonMotionDriver(e);e.s.dungeon.seen=[];const before=JSON.stringify(e.s);assert(!m.command(9,7,'d-sigil').ok);assert(!e.commandDungeonInteract('arden','d-sigil').ok);assert.equal(JSON.stringify(e.s),before)});
await test('R17','Every dungeon landmark has a route after clearing guards',()=>{const {e}=dungeon();for(const o of C.D.dungeon.objects){if(o.t==='enemy')e.s.dungeon.objects[o.id].status='defeated'}for(const o of C.D.dungeon.objects)assert.notEqual(e.dungeonPath(o.x,o.y,true),null,o.id)});
await test('R18','Every dungeon bridge connects two navigable cells',()=>{const {e}=dungeon();for(const p of C.D.dungeon.bridges){assert(e.dungeonPassable(p.x,p.y));const n=[[1,0],[-1,0],[0,1],[0,-1]].filter(([x,y])=>e.dungeonPassable(p.x+x,p.y+y));assert(n.length>=2,JSON.stringify(p))}});
await test('R19','Dungeon transition preserves the surface hero coordinate',()=>{const {e}=H.fixture(),before={x:e.s.heroes.arden.x,y:e.s.heroes.arden.y};e.enterDungeon('arden');e.commandDungeonMove('arden',3,8);e.leaveDungeon();assert.equal(e.s.dungeon.inside,null);assert.deepEqual({x:e.s.heroes.arden.x,y:e.s.heroes.arden.y},before)});
await test('R20','Dungeon battle save/load retains source, units, turn and campaign',()=>{const {e}=dungeon();e.s.dungeon.x=4;e.s.dungeon.y=8;assert(e.startBattle('arden',{kind:'dungeon',id:'d-guard'}).ok);const r=C.decode(C.envelope(e.export()));assert.deepEqual(r.battle,e.s.battle);assert.deepEqual(r.dungeon,e.s.dungeon);const restored=new C.Engine({state:r,scheduler:new H.Clock().scheduler()});restored.resume();assert.equal(restored.s.battle.source.id,'d-guard');assert(!restored.leaveDungeon().ok)});
await test('R21','Dungeon battle result removes only the defeated source and persists',()=>{const {e}=dungeon();e.s.dungeon.x=4;e.s.dungeon.y=8;e.startBattle('arden',{kind:'dungeon',id:'d-guard'});e.finishBattle('win');const r=C.decode(C.envelope(e.export()));assert.equal(r.dungeon.objects['d-guard'].status,'defeated');assert.equal(r.dungeon.objects['d-coven'].status,'active');assert(r.enemy.alive)});
await test('R22','Battle animation snapshots cannot change HP, RNG or rewards',()=>{const {e,b}=H.duel(),t=new B.BattleTimeline();t.observe(b,0,14);b.stacks[1].hp-=10;t.observe(b,20,14);const before=JSON.stringify(e.s);for(let time=20;time<2000;time+=17){for(const st of b.stacks)t.pose(st,time);t.busy(time)}assert.equal(JSON.stringify(e.s),before);assert.notEqual(t.snapshot,b)});
await test('R23','Ranged attacks and spells have separate projectile events',()=>{const {b}=H.duel();b.stacks[0].type='bows';const t=new B.BattleTimeline();t.observe(b,0,14);b.stacks[1].hp-=10;t.observe(b,100,14);assert(t.events.some(e=>e.type==='ranged'));b.stacks[1].hp-=10;t.observe(b,900,10);assert(t.events.some(e=>e.type==='spell'))});
await test('R24','Final killing blow is available to the death timeline before battle clear',()=>{let final;const {e,b}=H.duel();e.onEvent=event=>{if(event.type==='battleEnd')final=event.battle};const t=new B.BattleTimeline();t.observe(b,0,14);b.stacks[1].hp=0;b.stacks[1].qty=0;e.finishBattle('win');assert(final);t.observe(final,100,14);t.observe(null,100,0);assert(t.events.some(e=>e.type==='death'));assert(t.busy(200));assert(!t.busy(1000))});
await test('R25','A new battle discards all previous visual events',()=>{const {t,b}=R.timeline();b.stacks[1].hp-=20;t.observe(b,10,14);assert(t.busy(100));const other=C.clone(b);other.id='new-battle';t.observe(other,101,14);assert.equal(t.events.length,0);assert.equal(t.id,'new-battle')});
await test('R26','9.1.x save migration retains progress and settings',()=>{const {e}=dungeon();const s=e.export();s.gameVersion='9.1.2';s.day=126;s.week=18;s.month=5;s.objects.sawmill.owner='player';s.dungeon.objects['d-sigil'].status='completed';s.troopLevels.pikes=3;s.settings.musicVolume=.17;const r=C.decode(C.envelope(s));assert.equal(r.gameVersion,C.D.VERSION);assert.equal(r.day,126);assert.equal(r.objects.sawmill.owner,'player');assert.equal(r.dungeon.objects['d-sigil'].status,'completed');assert.equal(r.troopLevels.pikes,3);assert.equal(r.settings.musicVolume,.17)});
await test('R27','Defeated threatening force clears stale 54/92/100 threat on load',()=>{for(const threat of [54,92,100]){const s=C.initialState(1);s.enemy.alive=false;s.q.threat=threat;s.q.siege=true;const r=C.decode(C.envelope(s));assert.equal(r.q.threat,0);assert.equal(r.q.siege,false);assert.equal(r.q.siegeResolved,true);assert.equal(r.objects.necropolis.status,'active')}});
await test('R28','Direct engine restore and every later day maintain no-source invariant',()=>{const s=C.initialState(1);s.enemy.alive=false;s.q.threat=92;s.q.siege=true;const e=new C.Engine({state:s,scheduler:new H.Clock().scheduler()});assert.equal(e.s.q.threat,0);for(let i=0;i<10;i++){e.nextDay();assert.equal(e.s.q.threat,0);assert.equal(e.s.q.siege,false);assert(e.s.q.siegeResolved)}});
await test('R29','Living enemy still captures economy and raises threat',()=>{const {e}=H.fixture(),o=C.D.byId.sawmill;e.s.enemy.x=o.x;e.s.enemy.y=o.y+1;e.s.objects[o.id].owner='player';const before=e.s.q.threat;e.enemyWorldTurn();assert.equal(e.s.objects[o.id].owner,'enemy');assert(e.s.q.threat>before);assert(!C.solidAt(e.s,e.s.enemy.x,e.s.enemy.y))});
await test('R30','Garrison/citadel siege survives renderer migration',()=>{const {e}=H.fixture();e.s.enemy.x=13;e.s.enemy.y=7;e.s.garrison.pikes=100;e.s.build.citadel=true;e.s.build.barracks=true;e.enemyWorldTurn();assert.equal(e.s.q.siegeWins,1);assert.equal(e.s.q.siege,false);assert(e.s.enemy.alive)});
await test('R31','No threat source closes the siege quest in the UI',async()=>{const h=await app(),s=h.app.engine.export();s.enemy.alive=false;s.q.siege=true;s.q.threat=92;h.app.installEngine(s);h.app.renderQuests();assert(h.doc.getElementById('quests').innerHTML.includes('✅ Угроза осады Стального Холма устранена'));assert(h.app.engine.s.q.siegeResolved);assert(!h.doc.getElementById('threatHud').textContent.includes('92'))});
await test('R32','Canvas draw is pure, cached and DPR-capped on both worlds',()=>{for(const d of [false,true]){const h=R.worldFixture(d),before=JSON.stringify(h.e.s);h.world.draw(h.e.s,h.m,null,0);h.world.draw(h.e.s,h.m,null,1000);assert.equal(JSON.stringify(h.e.s),before);assert.equal(h.world.staticBuilds,1);assert.equal(h.canvas.width,780);assert(h.contexts[0].calls.some(c=>c[0]==='drawImage'&&c[1]?.src==='assets/world-sprites.png'))}});
await test('R33','Hidden tab cancels RAF, music and gestures; return resumes',async()=>{const h=await app();let stopped=0;h.app.music={stop(){stopped++}};h.app.pointer.down(1,10,20);h.doc.hidden=true;for(const fn of h.doc.listeners.visibilitychange)fn();assert.equal(h.frames.size,0);assert.equal(h.app.pointer.points.size,0);assert.equal(stopped,1);h.doc.hidden=false;for(const fn of h.doc.listeners.visibilitychange)fn();assert(h.frames.size>0)});
await test('R34','Six scored themes use lead, harmony, bass, arpeggio and multiple timbres',()=>{assert.deepEqual(Object.keys(M.THEMES),['world','city','danger','battle','abyss','siege']);for(const theme of Object.values(M.THEMES)){const a=audio(),m=new M.MusicEngine(a,new H.Clock().scheduler());m.bus=a.createGain();m.playStep(theme,0);assert(a.voices.length>=6);assert(new Set(a.voices.map(v=>v.type)).size>=3);assert(theme.melody.length>=16);assert(theme.chords.length>=4)}});
await test('R35','Music crossfade retirement and all audio timers stop cleanly',()=>{const a=audio(),clock=new H.Clock(),m=new M.MusicEngine(a,clock.scheduler());m.set('world',true,.3);const old=m.bus;m.set('battle',true,.2);assert.notEqual(m.bus,old);assert.equal(m.retired.size,1);m.stop();assert.equal(clock.jobs.size,0);assert.equal(m.retired.size,0);assert.equal(m.voices.size,0);assert(old.disconnected);assert(a.voices.every(v=>v.stopped))});
await test('R36','Music switches and volume retain zero correctly',()=>{const {e}=H.fixture();assert(e.setMusicVolume(0).ok);e.setMusic(false);e.setSound(false);const r=C.decode(C.envelope(e.export()));assert.equal(r.settings.musicVolume,0);assert.equal(r.settings.music,false);assert.equal(r.settings.sound,false);assert(!e.setMusicVolume(2).ok)});
await test('R37','Battle pointer cancel, drag and multi-touch cannot issue actions',async()=>{const h=await app(),a=h.app;H.place(a.engine,'arden',8,2);a.engine.startBattle('arden',{kind:'object',id:'object-8-3'});let count=0;a.engine.battleAction=()=>count++;a.battleScene.hit=()=>({action:{type:'wait'},battleId:'a',turnId:1});const p=a.battlePointer;p.down(1,5,5);p.cancel();p.up(1,5,5);p.down(1,5,5);p.move(1,25,25);p.up(1,25,25);p.down(1,5,5);p.down(2,10,10);p.up(2,10,10);p.up(1,5,5);assert.equal(count,0);p.down(1,5,5);p.up(1,5,5);assert.equal(count,1)});
await test('R38','Required atlases exist locally with intact source frames',()=>{for(const file of C.D.imageFiles)assert(fs.existsSync(path.join(__dirname,'..',file)),file);for(const f of S.actorFrames){assert(f.every(Number.isFinite));assert(f[0]>=0&&f[1]>=0&&f[0]+f[2]<=1254&&f[1]+f[3]<=1254)}assert.equal(S.actorFrames.length,12)});
await test('R39','Service-worker ignores QA, sibling navigation and foreign resources',()=>{const events={},scope='https://example.test/game/';vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../sw.js'),'utf8'),{URL,Set,Promise,self:{registration:{scope},addEventListener:(k,f)=>events[k]=f}});for(const url of [scope+'qa/visual.html?qa=1',scope+'readme.html','https://example.test/other/']){let handled=false;events.fetch({request:{method:'GET',url,mode:'navigate'},respondWith(){handled=true}});assert(!handled,url)}});
await test('R40','Service-worker and manifest identify the current release',()=>{const sw=fs.readFileSync(path.join(__dirname,'../sw.js'),'utf8'),manifest=JSON.parse(fs.readFileSync(path.join(__dirname,'../manifest.webmanifest'),'utf8'));assert(sw.includes("VERSION='"+C.D.VERSION+"'"));assert(sw.includes("cache:'no-store'"));assert(manifest.name.includes(C.D.VERSION));for(const f of ['scene-camera.js','scene-renderer.js','scene-battle.js','music-engine.js','game.css'])assert(sw.includes("'"+f+"'"))});
await test('R41','Roaming actor interpolates independently from its committed model coordinate',()=>{const h=R.worldFixture();h.world.observe(h.e.s,0);h.e.s.enemy.x--;h.world.observe(h.e.s,100);assert(h.world.enemyTrack);const before=JSON.stringify(h.e.s);h.world.draw(h.e.s,h.m,null,250);assert.equal(JSON.stringify(h.e.s),before);assert.notEqual(h.world.enemyTrack.from.x,h.world.enemyTrack.to.x)});
await test('R42','Capture VFX stays outside saved state and expires',()=>{const h=R.worldFixture();h.world.camera.centerOn(h.world.projection.cell(C.D.byId.sawmill.x,C.D.byId.sawmill.y));h.world.draw(h.e.s,h.m,null,1);h.e.s.objects.sawmill.owner='player';const before=JSON.stringify(h.e.s);h.world.draw(h.e.s,h.m,null,10);assert.equal(h.world.captureFx.length,1);assert.equal(JSON.stringify(h.e.s),before);h.world.draw(h.e.s,h.m,null,1500);assert.equal(h.world.captureFx.length,0)});
await test('R43','Corrupt dungeon coordinates, object status and music volume fail explicitly',()=>{for(const mutate of [s=>s.dungeon.x=0,s=>s.dungeon.seen=['99,99'],s=>s.dungeon.objects['d-ore'].status='unknown',s=>delete s.dungeon.objects['d-sigil'],s=>s.settings.musicVolume=5]){const s=C.initialState(1);mutate(s);assert.throws(()=>C.decode(C.envelope(s)))}});
await test('R44','Healing and non-damaging spells have presentation events',()=>{const {t,b}=R.timeline();b.stacks[0].hp+=1;t.observe(b,10,10);assert(t.events.some(e=>e.type==='heal'&&e.healing===1));assert(t.events.some(e=>e.type==='cast'));assert(t.busy(50));assert(!t.busy(800))});
await test('R45','Attack hit test accepts the upper sprite, not only its ground anchor',()=>{const h=R.harness(),{b}=H.duel(),scene=new B.BattleScene(h.canvas,h.doc,h.assets);b.stacks[1].x=1;b.stacks[1].y=0;scene.draw(b,0);const target=scene.targets.find(t=>t.action.type==='attack'),q=scene.camera.worldToScreen(target.px,target.py-90);assert.equal(scene.hit(q.x,q.y).action.targetId,'e')});
await test('R46','Battle ground hit testing covers entire valid diamonds without gaps',()=>{const h=R.harness(),{b}=H.duel(),scene=new B.BattleScene(h.canvas,h.doc,h.assets);scene.draw(b,0);for(const t of scene.targets.filter(t=>t.action.type==='move'))for(const [dx,dy]of [[.4,.4],[-.4,.4],[.4,-.4],[-.4,-.4]]){const p=scene.projection.cell(t.x+dx,t.y+dy),q=scene.camera.worldToScreen(p.x,p.y),hit=scene.hit(q.x,q.y);assert(hit);assert.equal(hit.x,t.x);assert.equal(hit.y,t.y)}});
await test('R47','Canvas pointer moves the selected stack once and locks repeat input during animation',async()=>{const h=await app(),a=h.app;H.place(a.engine,'arden',8,2);a.engine.s.heroes.arden.army.griffins=1;a.engine.startBattle('arden',{kind:'object',id:'object-8-3'});const target=a.battleScene.targets.find(t=>t.action.type==='move'),q=a.battleScene.camera.worldToScreen(target.px,target.py),before=a.engine.s.revision;a.battlePointer.down(1,q.x,q.y);a.battlePointer.up(1,q.x,q.y);assert(a.engine.s.revision>before);const after=a.engine.s.revision;a.battlePointer.down(1,q.x,q.y);a.battlePointer.up(1,q.x,q.y);assert.equal(a.engine.s.revision,after);assert(a.battleScene.timeline.busy(a.now()))});
await test('R48','Opening a menu cancels offscreen camera animation and the idle RAF loop',async()=>{const h=await app();h.app.camera.animateTo(1400,900);h.app.dungeonCamera.animateTo(500,500);h.app.switchScreen('hero');h.frame(20);assert.equal(h.app.camera.target,null);assert.equal(h.app.dungeonCamera.target,null);assert.equal(h.frames.size,0);const s=h.app.engine.export();s.enemy.alive=false;s.q.threat=92;s.q.siege=true;h.app.engine.replaceState(s);assert.equal(h.app.engine.s.q.threat,0);assert.equal(h.app.engine.s.q.siege,false)});
fs.writeFileSync(path.join(__dirname,'../qa/renderer-results.json'),JSON.stringify({total:results.length,passed:results.filter(r=>r.status==='pass').length,failed:results.filter(r=>r.status==='fail').length,results},null,2));console.log(JSON.stringify({total:results.length,passed:results.filter(r=>r.status==='pass').length,failed:results.filter(r=>r.status==='fail').length}));if(results.some(r=>r.status==='fail'))process.exitCode=1;
}
main();
