'use strict';
/* Snapshot-driven visual timeline: no callback here can apply damage, XP or turns. */
(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory(require('./game-core.js'),require('./scene-camera.js'),require('./scene-renderer.js'));else root.AshBattleScene=factory(root.AshCore,root.AshCamera,root.AshScene)})(typeof globalThis!=='undefined'?globalThis:this,(C,{Camera,Projection},S)=>{
class BattleTimeline{
 constructor(){this.id=null;this.snapshot=null;this.events=[];this.holdUntil=0}
 observe(b,now,mana){if(!b){if(this.snapshot&&this.id){this.holdUntil=Math.max(this.holdUntil,now+420);this.id=null}return}if(b.id!==this.snapshot?.id){this.events=[];this.snapshot=C.clone(b);this.id=b.id;this.mana=mana;return}const old=this.snapshot,actor=old.stacks.find(st=>st.id===old.selectedId),spell=mana<this.mana;if(spell&&actor)this.events.push({type:'cast',id:actor.id,stack:C.clone(actor),start:now,duration:600});for(const st of b.stacks){const prev=old.stacks.find(p=>p.id===st.id);if(!prev)continue;if(prev.x!==st.x||prev.y!==st.y)this.events.push({type:'move',id:st.id,from:{x:prev.x,y:prev.y},to:{x:st.x,y:st.y},start:now,duration:500});if(st.hp>prev.hp)this.events.push({type:'heal',id:st.id,stack:C.clone(st),healing:st.hp-prev.hp,start:now,duration:700});if(st.hp<prev.hp){this.events.push({type:st.hp<=0?'death':'hit',id:st.id,stack:C.clone(prev),damage:prev.hp-st.hp,start:now,duration:700});if(actor&&actor.id!==st.id)this.events.push({type:spell?'spell':C.stackDef(actor).range>1?'ranged':'melee',id:actor.id,from:{x:actor.x,y:actor.y},to:{x:st.x,y:st.y},start:now,duration:600,griffin:actor.type==='griffins',mage:actor.type==='mages'})}}this.snapshot=C.clone(b);this.id=b.id;this.mana=mana;this.events=this.events.filter(e=>now<e.start+e.duration)}
 busy(now){return this.events.some(e=>now<e.start+e.duration)||now<this.holdUntil}
 pose(st,now){let x=st.x,y=st.y,alpha=1,lift=Math.sin(now/630+st.x)*.7,hit=false;for(const e of this.events){if(e.id!==st.id)continue;const t=Math.max(0,Math.min(1,(now-e.start)/e.duration));if(t>=1)continue;if(e.type==='move'){const q=t*t*(3-2*t);x=e.from.x+(e.to.x-e.from.x)*q;y=e.from.y+(e.to.y-e.from.y)*q;lift=Math.sin(t*Math.PI)*4}if(e.type==='melee'){const q=Math.sin(t*Math.PI)*.7;x=e.from.x+(e.to.x-e.from.x)*q;y=e.from.y+(e.to.y-e.from.y)*q;lift=e.griffin?Math.sin(t*Math.PI)*55:0}if(e.type==='hit'){x+=Math.sin(t*28)*.06;hit=t<.5}if(e.type==='death'){alpha=1-t;lift=-t*20}}return {x,y,alpha,lift,hit}}
}
class BattleScene{
 constructor(canvas,doc,assets){this.canvas=canvas;this.doc=doc;this.assets=assets;this.projection=new Projection(8,5);this.camera=new Camera({worldWidth:this.projection.worldWidth,worldHeight:this.projection.worldHeight,zoom:.4});this.camera.minZoom=.2;this.timeline=new BattleTimeline();this.targets=[];this.base=null;this.environment='';this.last=null}
 observe(b,now,mana){this.timeline.observe(b,now,mana);if(b)this.last=b}
 build(environment){this.environment=environment;const off=this.doc.createElement('canvas');off.width=this.projection.worldWidth;off.height=this.projection.worldHeight;const ctx=off.getContext('2d'),image=this.assets['assets/terrain-materials.png'];ctx.fillStyle=environment==='dungeon'?'#101c22':'#29362b';ctx.fillRect(0,0,off.width,off.height);const material=environment==='dungeon'?7:environment==='ruins'?5:environment==='plain'?6:0,sw=(image.naturalWidth||image.width)/3,sh=(image.naturalHeight||image.height)/3;for(let y=-1;y<6;y++)for(let x=-1;x<9;x++){const p=this.projection.cell(x,y),tile=environment==='dungeon'&&y===5?4:(environment==='dungeon'&&x===-1||environment==='river'&&y===5)?3:material;ctx.save();S.diamond(ctx,p,this.rx+1,this.ry+1);ctx.clip();ctx.drawImage(image,(tile%3)*sw,Math.floor(tile/3)*sh,sw,sh,p.x-this.rx-1,p.y-this.ry-1,this.rx*2+2,this.ry*2+2);ctx.restore()}for(let i=0;i<12;i++){const p=this.projection.cell(i%8,i<8?-1:5);if(environment==='plain'&&i%3)continue;S.atlas(ctx,this.assets['assets/world-sprites.png'],['dungeon','ruins','river'].includes(environment)?11:10,4,4,p.x,p.y,130,170)}this.base=off}
 hit(x,y){const p=this.camera.screenToWorld(x,y);const enemies=this.targets.filter(t=>t.action.type==='attack').sort((a,b)=>b.py-a.py);for(const t of enemies)if(Math.abs(p.x-t.px)<=42&&p.y>=t.py-140&&p.y<=t.py+22)return t;const u=(p.x-(5*this.rx+50))/this.rx,v=(p.y-100)/this.ry-1,cx=Math.round((u+v)/2),cy=Math.round((v-u)/2);return this.targets.find(t=>t.x===cx&&t.y===cy)||null}
 draw(b,now=0){b=b||this.timeline.snapshot;if(!b)return;const r=this.canvas.getBoundingClientRect();if(!r.width)return;const dpr=Math.min(2,this.doc.defaultView?.devicePixelRatio||1);const cw=Math.round(r.width*dpr),ch=Math.round(r.height*dpr);if(this.canvas.width!==cw)this.canvas.width=cw;if(this.canvas.height!==ch)this.canvas.height=ch;const source=C.D.byId[b.source?.id],nearWater=source&&[[1,0],[-1,0],[0,1],[0,-1]].some(([dx,dy])=>C.D.terrain[source.y+dy]?.[source.x+dx]==='water'),nearRuins=source&&C.D.objects.some(o=>o.t==='ruins'&&C.distance(o,source)<4),env=b.source?.kind==='dungeon'?'dungeon':nearWater?'river':nearRuins?'ruins':source&&source.y>14?'plain':'forest',portrait=r.width<600;if(this.portrait!==portrait){this.portrait=portrait;this.rx=portrait?39:78;this.ry=portrait?54:42;const rx=this.rx,ry=this.ry;this.projection={worldWidth:13*rx+100,worldHeight:13*ry+180,cell:(x,y)=>({x:5*rx+50+(x-y)*rx,y:100+(x+y+1)*ry})};this.camera.worldWidth=this.projection.worldWidth;this.camera.worldHeight=this.projection.worldHeight;this.base=null}if(!this.base||this.environment!==env)this.build(env);const cam=this.camera,p=this.projection;cam.resize(r.width,r.height);cam.zoom=Math.min(r.width/(p.worldWidth-40),(r.height-25)/(p.worldHeight-60));cam.minZoom=.15;cam.centerOn(p.worldWidth/2,p.worldHeight*.48);const ctx=this.canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle=env==='dungeon'?'#0b131a':'#25352a';ctx.fillRect(0,0,r.width,r.height);ctx.save();ctx.scale(cam.zoom,cam.zoom);ctx.translate(-cam.x,-cam.y);ctx.drawImage(this.base,0,0);const selected=C.selectedStack(b),canAct=b.phase==='player'&&!this.timeline.busy(now);this.targets.length=0;
 for(let y=0;y<5;y++)for(let x=0;x<8;x++){const q=p.cell(x,y),occ=C.stackAt(b,x,y),attack=canAct&&occ&&occ.side!=='p'&&C.distance(selected,occ)<=C.stackDef(selected).range,move=canAct&&!occ&&!!C.tacticalPath(b,selected,x,y);if(move||attack||occ?.id===b.selectedId){S.diamond(ctx,q,this.rx-3,this.ry-3);ctx.fillStyle=attack?'rgba(200,58,51,.2)':'rgba(205,188,125,.045)';ctx.fill();ctx.strokeStyle=attack?'rgba(239,123,91,.65)':occ?.id===b.selectedId?'#f4d48c':'rgba(229,216,169,.16)';ctx.lineWidth=occ?.id===b.selectedId?3:1;ctx.stroke()}if(move||attack)this.targets.push({x,y,px:q.x,py:q.y,action:attack?{type:'attack',targetId:occ.id}:{type:'move',x,y},battleId:b.id,turnId:b.turnId})}
 const stacks=b.stacks.filter(st=>st.hp>0);for(const e of this.timeline.events)if(e.type==='death'&&now<e.start+e.duration&&!stacks.some(s=>s.id===e.id))stacks.push(e.stack);const actors=stacks.map(st=>({st,pose:this.timeline.pose(st,now)})).sort((a,b)=>(a.pose.x+a.pose.y)-(b.pose.x+b.pose.y));
 for(const {st,pose}of actors){const q=p.cell(pose.x,pose.y);S.shadow(ctx,q.x,q.y,29,pose.alpha*.36);if(st.id===b.selectedId){ctx.strokeStyle='#e8c36e';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(q.x,q.y,32,15,0,0,7);ctx.stroke()}const h=st.type==='griffins'?156:145,w=h*.76;ctx.save();if(st.side==='e'){ctx.translate(q.x*2,0);ctx.scale(-1,1)}S.atlas(ctx,this.assets['assets/actors-v2.png'],S.actorIndex[st.type]??8,4,3,q.x,q.y-pose.lift,w,h,pose.alpha);ctx.restore();}
 // Quantities are an interaction layer, drawn after every body so neighbours cannot hide them.
 for(const {st,pose}of actors){const q=p.cell(pose.x,pose.y);if(st.hp>0){ctx.fillStyle=st.side==='p'?'#163c52':'#572d27';ctx.fillRect(q.x-25,q.y+3,50,24);ctx.strokeStyle='#c6b887';ctx.lineWidth=1;ctx.strokeRect(q.x-25,q.y+3,50,24);ctx.font='bold 20px Georgia';ctx.textAlign='center';ctx.fillStyle='#fff0d0';ctx.fillText(st.qty,q.x,q.y+22)}}
 for(const e of this.timeline.events){const t=(now-e.start)/e.duration;if(t<0||t>1)continue;const a=e.from&&p.cell(e.from.x,e.from.y),z=e.to&&p.cell(e.to.x,e.to.y);if(e.type==='ranged'||e.type==='spell'){const q=Math.min(1,t*1.4),x=a.x+(z.x-a.x)*q,y=a.y-70+(z.y-a.y)*q-Math.sin(q*Math.PI)*50;ctx.strokeStyle=e.type==='spell'||e.mage?'#92dffd':'#dfc99b';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x-(z.x-a.x)*.07,y-(z.y-a.y)*.07);ctx.lineTo(x,y);ctx.stroke();if(e.type==='spell'||e.mage){ctx.fillStyle='#b6ebff';ctx.beginPath();ctx.arc(x,y,7+Math.sin(t*9)*2,0,7);ctx.fill()}}if(e.type==='cast'){const q=p.cell(e.stack.x,e.stack.y);ctx.strokeStyle='#9fddfa';ctx.lineWidth=3;ctx.beginPath();ctx.arc(q.x,q.y-60,15+t*22,0,Math.PI*2);ctx.stroke()}if(e.damage||e.healing){const q=p.cell(e.stack.x,e.stack.y);ctx.globalAlpha=1-t;ctx.font='bold 28px Georgia';ctx.fillStyle=e.healing?'#a9e6bb':'#ffc995';ctx.textAlign='center';ctx.fillText(e.healing?'+'+e.healing:'−'+e.damage,q.x,q.y-80-t*45);ctx.globalAlpha=1}}
 if(env==='dungeon'){for(let i=0;i<8;i++){const q=p.cell(i,5);const g=ctx.createRadialGradient(q.x,q.y,0,q.x,q.y,100);g.addColorStop(0,`rgba(233,91,34,${.2+Math.sin(now/440+i)*.03})`);g.addColorStop(1,'rgba(233,91,34,0)');ctx.fillStyle=g;ctx.fillRect(q.x-100,q.y-100,200,200)}}ctx.restore();
 }
}
return {BattleTimeline,BattleScene};});
