'use strict';
const assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const UI=require('../game-ui.js'),{environment}=require('./mock-dom.cjs');
module.exports=async({test,C,H})=>{
 async function boot(options){const f=environment(options),app=new UI.App(f.env);await app.boot();return {...f,app}}
 await test('T61','UI boots with valid state, all resources and closed startup dialog',async()=>{const {app,doc}=await boot();assert(app.ready);assert(!app.engine.s.q.tutorialTown);assert(doc.getElementById('startupModal').classList.contains('hidden'));assert.equal(doc.querySelector('main').inert,false)});
 await test('T62','Loaded combat opens its modal and restores selected stack/action availability',async()=>{const {e}=H.duel(),storage=new H.MemoryStorage();new C.SaveRepository(storage).save(e.export());const {app,doc}=await boot({storage});assert(app.engine.s.battle);assert(!doc.getElementById('battleModal').classList.contains('hidden'));assert.equal(doc.getElementById('bgrid').children.length,40);assert(!doc.getElementById('waitBtn').disabled);assert(doc.querySelector('main').inert)});
 await test('T63','Rendering every screen does not mutate game state or revision',async()=>{const {app}=await boot();const before=app.engine.export();for(const screen of ['map','hero','town','magic','quests','settings']){app.screen=screen;app.render()}assert.deepEqual(app.engine.export(),before)});
 await test('T64','Missing required image blocks gameplay and exposes retry',async()=>{const {app,doc}=await boot({missing:['assets/world-sprites.png']});assert(!app.ready);assert.equal(app.engine,null);assert(!doc.getElementById('retryLoad').hidden);assert.match(doc.getElementById('startupMessage').textContent,/world-sprites/)});
 await test('T65','Missing optional hero portrait falls back to a loaded original image',async()=>{const {app,doc,frame}=await boot({missing:['mage-portrait.jpg']});app.engine.selectHero('lyra');app.renderHero();frame(0);assert(app.ready);assert.equal(doc.getElementById('heroPortrait').src,'mage.jpg');assert(doc.drawn.includes('assets/actors-v2.png'));assert(!doc.drawn.includes(undefined))});
 await test('T66','A hanging image terminates with a recoverable loading error',async()=>{const f=environment({hang:['assets/world-sprites.png']}),app=new UI.App(f.env);const pending=app.boot();await Promise.resolve();f.clock.tick(15000);await pending;assert(!app.ready);assert(!f.doc.getElementById('retryLoad').hidden)});
 await test('T67','Double Next Day click advances exactly one day',async()=>{const {app,doc}=await boot();doc.getElementById('endDay').click();doc.getElementById('endDay').click();assert.equal(app.engine.s.day,2);assert(doc.getElementById('endDay').disabled)});
 await test('T68','Battle UI disables commands synchronously after accepting a move',async()=>{const {e}=H.duel(),storage=new H.MemoryStorage();new C.SaveRepository(storage).save(e.export());const {app,doc}=await boot({storage});const move=doc.getElementById('bgrid').children.find(b=>b.classList.contains('move'));move.click();assert.equal(app.engine.s.battle.phase,'resolving');assert(doc.getElementById('waitBtn').disabled);assert(doc.getElementById('defBtn').disabled);assert(doc.getElementById('spellBtn').disabled)});
 await test('T69','Insufficient mana is explained and every unavailable spell is disabled',async()=>{const {e}=H.duel();e.s.heroes.arden.mana=0;const storage=new H.MemoryStorage();new C.SaveRepository(storage).save(e.export());const {app,doc}=await boot({storage});app.openSpells();const choices=doc.getElementById('spellChoices').children;assert.equal(choices.length,4);assert(choices.every(b=>b.disabled));assert(choices.every(b=>b.textContent.includes('мана')||b.textContent.includes('маны')))});
 await test('T70','Modal uses dialog semantics, locks background and closes back to the map',async()=>{const {app,doc}=await boot();doc.getElementById('objectListBtn').click();const modal=doc.getElementById('objectListModal');assert.equal(modal.getAttribute('role'),'dialog');assert.equal(modal.getAttribute('aria-modal'),'true');assert.equal(modal.getAttribute('aria-hidden'),'false');assert(doc.querySelector('main').inert);app.closeLocal();assert(!doc.querySelector('main').inert)});
 await test('T71','Map hit-testing ignores hidden objects and cannot use a hidden altar',async()=>{const {app}=await boot();app.engine.s.seen=[];app.camera.x=0;app.camera.y=0;app.camera.zoom=1;app.worldScene.hitAreas=[];const p=app.objectPosition(C.D.byId.altar),before=app.engine.s.heroes.arden.magic;app.mapTap(p.x,p.y);app.mapTap(p.x,p.y);assert.equal(app.selection,null);assert.equal(app.engine.s.heroes.arden.magic,before)});
 await test('T72','Town navigation, not hidden town rendering, completes the tutorial',async()=>{const {app,doc}=await boot();app.renderTown();assert(!app.engine.s.q.tutorialTown);doc.querySelector('[data-s="town"]').click();assert(app.engine.s.q.tutorialTown)});
 await test('T73','Input before resource readiness never reads undefined state',async()=>{const f=environment({hang:['assets/world-sprites.png']}),app=new UI.App(f.env);const booting=app.boot();assert.doesNotThrow(()=>f.doc.getElementById('mapCanvas').emit('pointerdown',{pointerId:1,clientX:10,clientY:20}));f.doc.getElementById('endDay').click();assert.equal(app.engine,null);await Promise.resolve();f.clock.tick(15000);await booting});
 await test('T74','Pending level choice is visible after reload and persists a selected skill',async()=>{const {e}=H.fixture();e.addXP('arden',100);const storage=new H.MemoryStorage();new C.SaveRepository(storage).save(e.export());const {app,doc}=await boot({storage});assert(!doc.getElementById('levelModal').classList.contains('hidden'));assert(doc.getElementById('levelChoices').children.length>0);doc.getElementById('levelChoices').children[0].click();assert.equal(app.engine.s.levelChoices.length,0);assert.equal(Object.keys(new C.SaveRepository(storage).load().state.heroes.arden.skills).length,1)});
 await test('T75','Visible label rectangle is a hit target independent of the circular hotspot',async()=>{const {app}=await boot();app.engine.s.seen=['12,7'];app.camera.x=0;app.camera.y=0;app.camera.zoom=1;app.worldScene.hitAreas=[{id:'castle',x:500,y:500,w:180,h:44}];app.mapTap(510,510);assert.equal(app.selection,'castle')});
 await test('T76','Persistence failures leave a persistent user-visible message without breaking UI',async()=>{const {app,doc,storage}=await boot();storage.fail=true;assert.doesNotThrow(()=>app.engine.setSound(false));assert(!doc.getElementById('persistentStatus').hidden);assert.match(doc.getElementById('persistentStatus').textContent,/сохранить/)});
 await test('T77','Invalid existing save produces recovery UI instead of fresh overwrite',async()=>{const storage=new H.MemoryStorage();storage.setItem(C.SAVE_KEY,'invalid');const {app,doc}=await boot({storage});assert(!app.ready);assert(!doc.getElementById('recoveryImport').hidden);assert(!doc.getElementById('recoveryNew').hidden);assert.equal(storage.getItem(C.SAVE_KEY),'invalid')});
 await test('T78','Cancelled New Game leaves current state and persistent save untouched',async()=>{const {app,env,storage}=await boot();env.confirm=()=>false;const s=app.engine.export(),saved=storage.getItem(C.SAVE_KEY);app.newGame();assert.deepEqual(app.engine.export(),s);assert.equal(storage.getItem(C.SAVE_KEY),saved)});
 await test('T79','Citadel is available in town UI and every building has a help button',async()=>{const {app,doc}=await boot();app.engine.s.gold=10000;app.engine.s.wood=20;app.engine.s.ore=20;app.engine.s.build.barracks=true;app.renderTown();const button=doc.querySelector('[data-build="citadel"]');assert(!button.disabled);assert.equal(doc.querySelectorAll('[data-build-help]').length,Object.keys(C.D.builds).length);assert(!doc.body.textContent.includes('эффект не определён'))});
 await test('T80','Mobile markup enables zoom, viewport-fitting battle grid and pointer cancellation',()=>{const html=fs.readFileSync(path.join(__dirname,'../index.html'),'utf8'),ui=fs.readFileSync(path.join(__dirname,'../game-ui.js'),'utf8');assert(html.includes('maximum-scale=1,user-scalable=no'));assert(html.includes('id="battleCanvas"'));assert(html.includes('Список клеток и целей'));assert(fs.readFileSync(path.join(__dirname,'../game.css'),'utf8').includes('touch-action:none'));assert(ui.includes("'pointercancel'"));assert(ui.includes("'lostpointercapture'"))});
 await test('T81','Imported names, extra heroes and object-coordinate overrides are rejected',()=>{for(const mutate of [s=>s.heroes.arden.name='<img onerror=alert(1)>',s=>s.heroes.evil=C.clone(s.heroes.arden),s=>s.objects.castle.x=0,s=>s.objects.castle.img='https://evil.test']){const s=C.initialState(1);mutate(s);assert.throws(()=>C.validateState(s))}});
 await test('T82','All unsigned 32-bit random seeds validate and boot correctly',()=>{for(const seed of [1,999999999,1000000001,2147483648,4294967295])C.validateState(C.initialState(seed))});
 await test('T83','Player can deliberately initiate combat with the roaming army',()=>{const {e}=H.fixture();H.place(e,'arden',14,11);assert(e.commandInteract('arden','morvein-field').ok);assert.equal(e.s.battle.source.kind,'roaming')});
 await test('T84','Arrival at the town opens its actual screen through an action event',async()=>{const {app}=await boot();H.place(app.engine,'arden',10,7);app.engine.commandInteract('arden','castle');while(app.engine.s.movement)app.engine.movementStep(app.engine.s.movement.id);assert.equal(app.screen,'town');assert(app.engine.s.q.tutorialTown)});
 await test('T85','Legacy XP missed by the old event code awards its level once on migration',()=>{const legacy=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures/legacy865.json'),'utf8'));legacy.heroes.arden.xp=100;const s=C.migrateLegacy(legacy);assert.equal(s.heroes.arden.level,2);assert.equal(s.heroes.arden.atk,3);assert.equal(s.levelChoices.length,1);assert.deepEqual(C.decode(C.envelope(s)).heroes,s.heroes)});
 await test('T86','Hostile catalog keys and excessive legacy level queues are rejected',()=>{const s=C.initialState(1);s.heroes.arden.skills.toString=1;assert.throws(()=>C.validateState(s));const legacy=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures/legacy865.json'),'utf8'));legacy.heroes.arden.level=1000000000;assert.throws(()=>C.migrateLegacy(legacy))});
 await test('T87','A complete tactical battle resolves using only legal move/attack commands',()=>{const clock=new H.Clock(),e=new C.Engine({seed:4294967295,scheduler:clock.scheduler(),onChange:s=>C.validateState(s)});H.place(e,'arden',8,2);e.s.heroes.arden.army={pikes:24,bows:10,cavs:2,griffins:1,mages:2};e.startBattle('arden',{kind:'object',id:'object-8-3'});let turns=0;while(e.s.battle&&turns++<1000){const b=e.s.battle;if(b.phase!=='player'){clock.tick(100);continue}const a=C.selectedStack(b),targets=b.stacks.filter(st=>st.side==='e'&&st.hp>0),target=targets.find(t=>C.distance(a,t)<=C.stackDef(a).range);let command;if(target)command={type:'attack',targetId:target.id};else{let best=null;for(const t of targets){const p=C.search(a.x,a.y,(x,y)=>Math.abs(x-t.x)+Math.abs(y-t.y)<=C.stackDef(a).range&&!C.stackAt(b,x,y),(x,y)=>!C.stackAt(b,x,y),Infinity,8,5);if(p?.length&&(!best||p.length<best.length))best=p}if(best){const [x,y]=best[Math.min(best.length,C.stackDef(a).spd)-1];command={type:'move',x,y}}else command={type:'defend'}}assert(e.battleAction(command,b.id,b.turnId).ok)}assert.equal(e.s.battle,null);assert(turns<1000);C.validateState(e.export());assert.equal(e.s.objects['object-8-3'].status,'defeated')});
 await test('T88','Default seeded campaign events produce valid snapshots over repeated days',()=>{const e=new C.Engine({seed:4294967295,scheduler:new H.Clock().scheduler(),onChange:s=>C.validateState(s)});e.s.enemy.alive=false;for(let day=0;day<150;day++){while(e.s.levelChoices.length){const c=e.s.levelChoices[0];e.chooseSkill(c.id,c.options[0])}e.nextDay();C.validateState(C.decode(C.envelope(e.export())))}});
 await test('T89','Roaming army appears in the accessible object list when scouted',async()=>{const {app,doc}=await boot();app.engine.s.seen.push(C.key(app.engine.s.enemy.x,app.engine.s.enemy.y));app.engine.s.seen=[...new Set(app.engine.s.seen)];app.renderObjectList();assert(doc.getElementById('knownObjects').textContent.includes('Полевой отряд Морвейна'))});

 await test('T90','Optional unit image uses a loaded fallback in army cards and battle cells',async()=>{const {app,doc}=await boot({missing:['pikeman.jpg','pikeman-portrait.jpg']});app.renderHero();assert(!doc.getElementById('army').innerHTML.includes('pikeman.jpg'));assert(doc.getElementById('army').innerHTML.includes('hero-portrait.jpg'));H.place(app.engine,'arden',8,2);app.engine.startBattle('arden',{kind:'object',id:'object-8-3'});app.battleScene.draw(app.engine.s.battle,0);assert.equal(doc.getElementById('bgrid').querySelectorAll('.stack').length,0);assert(doc.drawn.includes('assets/actors-v2.png'));assert(!doc.drawn.includes('pikeman.jpg'))});
 await test('T91','Movement/day sounds require gesture unlock, honor mute and release nodes',async()=>{const {app,env,doc}=await boot(),played=[],disconnected=[];env.AudioContext=class{constructor(){this.state='running';this.currentTime=0;this.destination={}}createOscillator(){const node={frequency:{value:0},connect(){},start(){played.push(node.frequency.value)},stop(){node.onended?.()},disconnect(){disconnected.push('oscillator')}};return node}createGain(){return {gain:{value:0},connect(){},disconnect(){disconnected.push('gain')}}}};assert.equal(app.audio,null);doc.getElementById('endDay').click();assert.deepEqual(played,[520]);H.place(app.engine,'arden',12,8);app.engine.commandMove('arden',13,8);app.engine.movementStep(app.engine.s.movement.id);assert(played.includes(300));assert.equal(disconnected.length,played.length*2);app.engine.setSound(false);const count=played.length;app.engine.nextDay();assert.equal(played.length,count)});
 await test('T92','Unavailable or throwing audio cannot break game actions',async()=>{const {app,env,doc}=await boot();env.AudioContext=class{constructor(){throw Error('audio unavailable')}};assert.doesNotThrow(()=>doc.getElementById('endDay').click());assert.equal(app.engine.s.day,2)});
 await test('T93','Enemy contact defeats an unarmed hero without creating an invalid empty battle',()=>{const {e}=H.fixture();H.place(e,'arden',14,11);for(const k of Object.keys(e.s.heroes.arden.army))e.s.heroes.arden.army[k]=0;e.nextDay();assert.equal(e.s.battle,null);assert(C.atTown(e.s,'arden'));assert.equal(e.s.heroes.arden.moves,0);assert(e.s.enemy.alive);C.validateState(C.decode(C.envelope(e.export())))});

 await test('T94','HTML has one final document closure, unique IDs, image alternatives and complete local resources',()=>{const root=path.join(__dirname,'..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');assert.equal((html.match(/<\/html>/g)||[]).length,1);assert.equal((html.match(/<\/body>/g)||[]).length,1);assert(/<\/body>\s*<\/html>\s*$/.test(html));const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(ids).size,ids.length);for(const [,attrs]of html.matchAll(/<img\b([^>]+)>/g))assert(/\balt=/.test(attrs));for(const [,ref]of html.matchAll(/(?:src|href)="([^"#]+)"/g))assert(fs.existsSync(path.join(root,ref)),ref);for(const file of C.D.imageFiles)assert(fs.existsSync(path.join(root,file)),file)});
 await test('T95','Service worker installs a complete version and serves cached navigation offline',async()=>{const vm=require('node:vm'),events={},scope='https://example.test/game/',stored=new Map(),response={ok:true,clone(){return this}},added=[];const cache={addAll:async urls=>{for(const url of urls){assert(fs.existsSync(path.join(__dirname,'..',new URL(url).pathname.slice(new URL(scope).pathname.length))));added.push(url);stored.set(url,response)}},match:async url=>stored.get(url),put:async(url,value)=>stored.set(url,value)};const context={URL,Set,Promise,self:{registration:{scope},addEventListener:(k,fn)=>events[k]=fn},caches:{open:async()=>cache},fetch:async()=>{throw Error('offline')}};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../sw.js'),'utf8'),context);let pending;events.install({waitUntil:p=>pending=p});await pending;assert(added.includes(scope+'game-core.js'));assert(added.includes(scope+'assets/world-sprites.png'));events.fetch({request:{method:'GET',url:scope},respondWith:p=>pending=p});assert.equal(await pending,response);events.fetch({request:{method:'GET',url:scope+'game-ui.js?v=1'},respondWith:p=>pending=p});assert.equal(await pending,response)});
 await test('T96','Incomplete service-worker installation rejects instead of activating a partial version',async()=>{const vm=require('node:vm'),events={};vm.runInNewContext(fs.readFileSync(path.join(__dirname,'../sw.js'),'utf8'),{URL,Set,Promise,self:{registration:{scope:'https://example.test/game/'},addEventListener:(k,f)=>events[k]=f},caches:{open:async()=>({addAll:async()=>{throw Error('missing asset')}})}});let pending;events.install({waitUntil:p=>pending=p});await assert.rejects(pending,/missing asset/)});

 await test('T97','Roaming-army label hit-test resolves its dynamic object without static-catalog lookup',async()=>{const {app}=await boot();const enemy=app.engine.s.enemy;app.engine.s.seen.push(C.key(enemy.x,enemy.y));app.engine.s.seen=[...new Set(app.engine.s.seen)];app.camera.x=0;app.camera.y=0;app.camera.zoom=1;app.worldScene.hitAreas=[{id:enemy.id,x:500,y:500,w:150,h:44}];assert.doesNotThrow(()=>app.mapTap(510,510));assert.equal(app.selection,enemy.id)});

 await test('T98','Route HUD states path length and next-day reset without changing progress',async()=>{const {app,doc}=await boot();app.engine.commandMove('arden',13,8);const before=app.engine.export();app.render();assert(doc.getElementById('movesLabel').textContent.includes('путь 1'));assert(doc.getElementById('movesLabel').title.includes('сбросит маршрут'));assert.deepEqual(app.engine.export(),before)});

 await test('T99','Original combat stats, recruitment costs, original building costs, artifacts and enemy rewards are unchanged',()=>{const old=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures/balance865.json'),'utf8'));for(const k of ['units','enemies','artifactDefs'])assert.deepEqual(C.D[k],old[k]);for(const [k,d] of Object.entries(old.builds))assert.deepEqual({n:C.D.builds[k].n,cost:C.D.builds[k].cost,req:C.D.builds[k].req},d);for(const o of C.D.objects.filter(o=>o.t==='enemy')){const previous=o.legacyKeys.map(k=>old.enemySources[k]).find(Boolean);assert(previous);assert.deepEqual({stacks:o.stacks,reward:o.reward,xp:o.xp},previous)}});

};
